from py_sexpr.terms import *
from py_sexpr.stack_vm.emit import module_code
from os.path import join as _joinpath
def joinpath(a, b):
    global joinpath, __file__
    joinpath = _joinpath
    __file__ = _joinpath(a, b)
    return __file__
project_path = "C:\\Users\\twshe\\Desktop\\mydb\\com-haskell\\testing\\datatypes"
res = block( "No document"
           , assign( "ps_SmallPrelude"
                   , call( var('import_module')
                         , "datatypes.SmallPrelude.purescript_impl" ) )
           , assign( "ps_PADT1"
                   , define( "ps_PADT1"
                           , ["ps_value0"]
                           , block( set_item(this, "value0", var("ps_value0"))
                                  , ret(this) ) ) )
           , assign( "ps_PADT2"
                   , define( "ps_PADT2"
                           , ["ps_value0", "ps_value1"]
                           , block( set_item(this, "value0", var("ps_value0"))
                                  , set_item(this, "value1", var("ps_value1"))
                                  , ret(this) ) ) )
           , assign( "ps_PADT3"
                   , define( "ps_PADT3"
                           , ["ps_value0"]
                           , block( set_item(this, "value0", var("ps_value0"))
                                  , ret(this) ) ) )
           , assign("ps_PF", define(None, ["ps_x"], block(ret(var("ps_x")))))
           , assign( "ps_A"
                   , block( define("ps_A", [], block(this))
                          , set_attr(var("ps_A"), "value", new(var("ps_A")))
                          , var("ps_A") ) )
           , assign( "ps_B"
                   , block( define("ps_B", [], block(this))
                          , set_attr(var("ps_B"), "value", new(var("ps_B")))
                          , var("ps_B") ) )
           , assign( "ps_C"
                   , block( define("ps_C", [], block(this))
                          , set_attr(var("ps_C"), "value", new(var("ps_C")))
                          , var("ps_C") ) )
           , assign( "ps_ADT1"
                   , define( "ps_ADT1"
                           , ["ps_value0"]
                           , block( set_item(this, "value0", var("ps_value0"))
                                  , ret(this) ) ) )
           , assign( "ps_ADT2"
                   , define( "ps_ADT2"
                           , ["ps_value0", "ps_value1"]
                           , block( set_item(this, "value0", var("ps_value0"))
                                  , set_item(this, "value1", var("ps_value1"))
                                  , ret(this) ) ) )
           , assign( "ps_ADT3"
                   , define( "ps_ADT3"
                           , ["ps_value0"]
                           , block( set_item(this, "value0", var("ps_value0"))
                                  , ret(this) ) ) )
           , assign("ps_F", define(None, ["ps_x"], block(ret(var("ps_x")))))
           , assign( "ps_main"
                   , call( call( get_item(var("ps_SmallPrelude"), "discard")
                               , call( get_item( var("ps_SmallPrelude")
                                               , "println" )
                                     , metadata( 24
                                               , 13
                                               , joinpath( project_path
                                               , "src\\Main.purs" )
                                               , "enums:" ) ) )
                         , define( None
                                 , ["ps_$__unused"]
                                 , block( ret( call( call( get_item( var( "ps_SmallPrelude" )
                                                                   , "discard" )
                                                         , call( get_item( var( "ps_SmallPrelude" )
                                                                         , "println" )
                                                               , get_attr( var( "ps_A" )
                                                                         , "value" ) ) )
                                                   , define( None
                                                           , ["ps_$__unused"]
                                                           , block( ret( call( call( get_item( var( "ps_SmallPrelude" )
                                                                                             , "discard" )
                                                                                   , call( get_item( var( "ps_SmallPrelude" )
                                                                                                   , "println" )
                                                                                         , get_attr( var( "ps_B" )
                                                                                                   , "value" ) ) )
                                                                             , define( None
                                                                                     , [ "ps_$__unused" ]
                                                                                     , block( ret( call( call( get_item( var( "ps_SmallPrelude" )
                                                                                                                       , "discard" )
                                                                                                             , call( get_item( var( "ps_SmallPrelude" )
                                                                                                                             , "println" )
                                                                                                                   , get_attr( var( "ps_C" )
                                                                                                                             , "value" ) ) )
                                                                                                       , define( None
                                                                                                               , [ "ps_$__unused" ]
                                                                                                               , block( ret( call( call( get_item( var( "ps_SmallPrelude" )
                                                                                                                                                 , "discard" )
                                                                                                                                       , call( get_item( var( "ps_SmallPrelude" )
                                                                                                                                                       , "println" )
                                                                                                                                             , metadata( 29
                                                                                                                                                       , 13
                                                                                                                                                       , joinpath( project_path
                                                                                                                                                       , "src\\Main.purs" )
                                                                                                                                                       , "ordinary adts:" ) ) )
                                                                                                                                 , define( None
                                                                                                                                         , [ "ps_$__unused" ]
                                                                                                                                         , block( ret( call( call( get_item( var( "ps_SmallPrelude" )
                                                                                                                                                                           , "discard" )
                                                                                                                                                                 , call( get_item( var( "ps_SmallPrelude" )
                                                                                                                                                                                 , "println" )
                                                                                                                                                                       , new( var( "ps_ADT1" )
                                                                                                                                                                            , metadata( 30
                                                                                                                                                                                      , 19
                                                                                                                                                                                      , joinpath( project_path
                                                                                                                                                                                      , "src\\Main.purs" )
                                                                                                                                                                                      , "this is a string" ) ) ) )
                                                                                                                                                           , define( None
                                                                                                                                                                   , [ "ps_$__unused" ]
                                                                                                                                                                   , block( ret( call( call( get_item( var( "ps_SmallPrelude" )
                                                                                                                                                                                                     , "discard" )
                                                                                                                                                                                           , call( get_item( var( "ps_SmallPrelude" )
                                                                                                                                                                                                           , "println" )
                                                                                                                                                                                                 , new( var( "ps_ADT2" )
                                                                                                                                                                                                      , metadata( 31
                                                                                                                                                                                                                , 19
                                                                                                                                                                                                                , joinpath( project_path
                                                                                                                                                                                                                , "src\\Main.purs" )
                                                                                                                                                                                                                , 1 )
                                                                                                                                                                                                      , metadata( 31
                                                                                                                                                                                                                , 21
                                                                                                                                                                                                                , joinpath( project_path
                                                                                                                                                                                                                , "src\\Main.purs" )
                                                                                                                                                                                                                , 2.0 ) ) ) )
                                                                                                                                                                                     , define( None
                                                                                                                                                                                             , [ "ps_$__unused" ]
                                                                                                                                                                                             , block( ret( call( call( get_item( var( "ps_SmallPrelude" )
                                                                                                                                                                                                                               , "discard" )
                                                                                                                                                                                                                     , call( get_item( var( "ps_SmallPrelude" )
                                                                                                                                                                                                                                     , "println" )
                                                                                                                                                                                                                           , new( var( "ps_ADT3" )
                                                                                                                                                                                                                                , metadata( 32
                                                                                                                                                                                                                                          , 19
                                                                                                                                                                                                                                          , joinpath( project_path
                                                                                                                                                                                                                                          , "src\\Main.purs" )
                                                                                                                                                                                                                                          , record( ( "x"
                                                                                                                                                                                                                                                    , metadata( 32
                                                                                                                                                                                                                                                              , 24
                                                                                                                                                                                                                                                              , joinpath( project_path
                                                                                                                                                                                                                                                              , "src\\Main.purs" )
                                                                                                                                                                                                                                                              , 22 ) )
                                                                                                                                                                                                                                                  , ( "y"
                                                                                                                                                                                                                                                    , metadata( 32
                                                                                                                                                                                                                                                              , 32
                                                                                                                                                                                                                                                              , joinpath( project_path
                                                                                                                                                                                                                                                              , "src\\Main.purs" )
                                                                                                                                                                                                                                                              , 33 ) ) ) ) ) ) )
                                                                                                                                                                                                               , define( None
                                                                                                                                                                                                                       , [ "ps_$__unused" ]
                                                                                                                                                                                                                       , block( ret( call( call( get_item( var( "ps_SmallPrelude" )
                                                                                                                                                                                                                                                         , "discard" )
                                                                                                                                                                                                                                               , call( get_item( var( "ps_SmallPrelude" )
                                                                                                                                                                                                                                                               , "println" )
                                                                                                                                                                                                                                                     , new( var( "ps_ADT3" )
                                                                                                                                                                                                                                                          , metadata( 33
                                                                                                                                                                                                                                                                    , 22
                                                                                                                                                                                                                                                                    , joinpath( project_path
                                                                                                                                                                                                                                                                    , "src\\Main.purs" )
                                                                                                                                                                                                                                                                    , record( ( "x"
                                                                                                                                                                                                                                                                              , metadata( 33
                                                                                                                                                                                                                                                                                        , 27
                                                                                                                                                                                                                                                                                        , joinpath( project_path
                                                                                                                                                                                                                                                                                        , "src\\Main.purs" )
                                                                                                                                                                                                                                                                                        , 22 ) )
                                                                                                                                                                                                                                                                            , ( "y"
                                                                                                                                                                                                                                                                              , metadata( 33
                                                                                                                                                                                                                                                                                        , 35
                                                                                                                                                                                                                                                                                        , joinpath( project_path
                                                                                                                                                                                                                                                                                        , "src\\Main.purs" )
                                                                                                                                                                                                                                                                                        , 33 ) ) ) ) ) ) )
                                                                                                                                                                                                                                         , define( None
                                                                                                                                                                                                                                                 , [ "ps_$__unused" ]
                                                                                                                                                                                                                                                 , block( ret( call( call( get_item( var( "ps_SmallPrelude" )
                                                                                                                                                                                                                                                                                   , "discard" )
                                                                                                                                                                                                                                                                         , call( get_item( var( "ps_SmallPrelude" )
                                                                                                                                                                                                                                                                                         , "println" )
                                                                                                                                                                                                                                                                               , metadata( 35
                                                                                                                                                                                                                                                                                         , 13
                                                                                                                                                                                                                                                                                         , joinpath( project_path
                                                                                                                                                                                                                                                                                         , "src\\Main.purs" )
                                                                                                                                                                                                                                                                                         , "parametric adts:" ) ) )
                                                                                                                                                                                                                                                                   , define( None
                                                                                                                                                                                                                                                                           , [ "ps_$__unused" ]
                                                                                                                                                                                                                                                                           , block( ret( call( call( get_item( var( "ps_SmallPrelude" )
                                                                                                                                                                                                                                                                                                             , "discard" )
                                                                                                                                                                                                                                                                                                   , call( get_item( var( "ps_SmallPrelude" )
                                                                                                                                                                                                                                                                                                                   , "println" )
                                                                                                                                                                                                                                                                                                         , new( var( "ps_PADT1" )
                                                                                                                                                                                                                                                                                                              , metadata( 36
                                                                                                                                                                                                                                                                                                                        , 20
                                                                                                                                                                                                                                                                                                                        , joinpath( project_path
                                                                                                                                                                                                                                                                                                                        , "src\\Main.purs" )
                                                                                                                                                                                                                                                                                                                        , "this is a string" ) ) ) )
                                                                                                                                                                                                                                                                                             , define( None
                                                                                                                                                                                                                                                                                                     , [ "ps_$__unused" ]
                                                                                                                                                                                                                                                                                                     , block( ret( call( call( get_item( var( "ps_SmallPrelude" )
                                                                                                                                                                                                                                                                                                                                       , "discard" )
                                                                                                                                                                                                                                                                                                                             , call( get_item( var( "ps_SmallPrelude" )
                                                                                                                                                                                                                                                                                                                                             , "println" )
                                                                                                                                                                                                                                                                                                                                   , new( var( "ps_PADT2" )
                                                                                                                                                                                                                                                                                                                                        , metadata( 37
                                                                                                                                                                                                                                                                                                                                                  , 20
                                                                                                                                                                                                                                                                                                                                                  , joinpath( project_path
                                                                                                                                                                                                                                                                                                                                                  , "src\\Main.purs" )
                                                                                                                                                                                                                                                                                                                                                  , 1 )
                                                                                                                                                                                                                                                                                                                                        , metadata( 37
                                                                                                                                                                                                                                                                                                                                                  , 22
                                                                                                                                                                                                                                                                                                                                                  , joinpath( project_path
                                                                                                                                                                                                                                                                                                                                                  , "src\\Main.purs" )
                                                                                                                                                                                                                                                                                                                                                  , 2.0 ) ) ) )
                                                                                                                                                                                                                                                                                                                       , define( None
                                                                                                                                                                                                                                                                                                                               , [ "ps_$__unused" ]
                                                                                                                                                                                                                                                                                                                               , block( ret( call( call( get_item( var( "ps_SmallPrelude" )
                                                                                                                                                                                                                                                                                                                                                                 , "discard" )
                                                                                                                                                                                                                                                                                                                                                       , call( get_item( var( "ps_SmallPrelude" )
                                                                                                                                                                                                                                                                                                                                                                       , "println" )
                                                                                                                                                                                                                                                                                                                                                             , new( var( "ps_PADT3" )
                                                                                                                                                                                                                                                                                                                                                                  , metadata( 38
                                                                                                                                                                                                                                                                                                                                                                            , 20
                                                                                                                                                                                                                                                                                                                                                                            , joinpath( project_path
                                                                                                                                                                                                                                                                                                                                                                            , "src\\Main.purs" )
                                                                                                                                                                                                                                                                                                                                                                            , record( ( "x"
                                                                                                                                                                                                                                                                                                                                                                                      , metadata( 38
                                                                                                                                                                                                                                                                                                                                                                                                , 25
                                                                                                                                                                                                                                                                                                                                                                                                , joinpath( project_path
                                                                                                                                                                                                                                                                                                                                                                                                , "src\\Main.purs" )
                                                                                                                                                                                                                                                                                                                                                                                                , 22 ) )
                                                                                                                                                                                                                                                                                                                                                                                    , ( "y"
                                                                                                                                                                                                                                                                                                                                                                                      , metadata( 38
                                                                                                                                                                                                                                                                                                                                                                                                , 33
                                                                                                                                                                                                                                                                                                                                                                                                , joinpath( project_path
                                                                                                                                                                                                                                                                                                                                                                                                , "src\\Main.purs" )
                                                                                                                                                                                                                                                                                                                                                                                                , 33 ) )
                                                                                                                                                                                                                                                                                                                                                                                    , ( "z"
                                                                                                                                                                                                                                                                                                                                                                                      , metadata( 38
                                                                                                                                                                                                                                                                                                                                                                                                , 41
                                                                                                                                                                                                                                                                                                                                                                                                , joinpath( project_path
                                                                                                                                                                                                                                                                                                                                                                                                , "src\\Main.purs" )
                                                                                                                                                                                                                                                                                                                                                                                                , 2 ) ) ) ) ) ) )
                                                                                                                                                                                                                                                                                                                                                 , define( None
                                                                                                                                                                                                                                                                                                                                                         , [ "ps_$__unused" ]
                                                                                                                                                                                                                                                                                                                                                         , block( ret( call( get_item( var( "ps_SmallPrelude" )
                                                                                                                                                                                                                                                                                                                                                                                     , "println" )
                                                                                                                                                                                                                                                                                                                                                                           , metadata( 39
                                                                                                                                                                                                                                                                                                                                                                                     , 17
                                                                                                                                                                                                                                                                                                                                                                                     , joinpath( project_path
                                                                                                                                                                                                                                                                                                                                                                                     , "src\\Main.purs" )
                                                                                                                                                                                                                                                                                                                                                                                     , record( ( "it"
                                                                                                                                                                                                                                                                                                                                                                                               , new( var( "ps_PADT3" )
                                                                                                                                                                                                                                                                                                                                                                                                    , metadata( 39
                                                                                                                                                                                                                                                                                                                                                                                                              , 29
                                                                                                                                                                                                                                                                                                                                                                                                              , joinpath( project_path
                                                                                                                                                                                                                                                                                                                                                                                                              , "src\\Main.purs" )
                                                                                                                                                                                                                                                                                                                                                                                                              , record( ( "x"
                                                                                                                                                                                                                                                                                                                                                                                                                        , metadata( 39
                                                                                                                                                                                                                                                                                                                                                                                                                                  , 34
                                                                                                                                                                                                                                                                                                                                                                                                                                  , joinpath( project_path
                                                                                                                                                                                                                                                                                                                                                                                                                                  , "src\\Main.purs" )
                                                                                                                                                                                                                                                                                                                                                                                                                                  , 22 ) )
                                                                                                                                                                                                                                                                                                                                                                                                                      , ( "y"
                                                                                                                                                                                                                                                                                                                                                                                                                        , metadata( 39
                                                                                                                                                                                                                                                                                                                                                                                                                                  , 42
                                                                                                                                                                                                                                                                                                                                                                                                                                  , joinpath( project_path
                                                                                                                                                                                                                                                                                                                                                                                                                                  , "src\\Main.purs" )
                                                                                                                                                                                                                                                                                                                                                                                                                                  , 33 ) )
                                                                                                                                                                                                                                                                                                                                                                                                                      , ( "z"
                                                                                                                                                                                                                                                                                                                                                                                                                        , metadata( 39
                                                                                                                                                                                                                                                                                                                                                                                                                                  , 49
                                                                                                                                                                                                                                                                                                                                                                                                                                  , joinpath( project_path
                                                                                                                                                                                                                                                                                                                                                                                                                                  , "src\\Main.purs" )
                                                                                                                                                                                                                                                                                                                                                                                                                                  , 2 ) ) ) ) ) ) ) ) ) ) ) ) ) ) ) ) ) ) ) ) ) ) ) ) ) ) ) ) ) ) ) ) ) ) ) ) ) ) ) ) ) ) ) ) ) ) ) ) ) ) ) ) ) ) ) ) ) ) ) ) ) )
           , assign( "exports"
                   , record( ("A", var("ps_A"))
                           , ("B", var("ps_B"))
                           , ("C", var("ps_C"))
                           , ("ADT1", var("ps_ADT1"))
                           , ("ADT2", var("ps_ADT2"))
                           , ("ADT3", var("ps_ADT3"))
                           , ("F", var("ps_F"))
                           , ("PADT1", var("ps_PADT1"))
                           , ("PADT2", var("ps_PADT2"))
                           , ("PADT3", var("ps_PADT3"))
                           , ("PF", var("ps_PF"))
                           , ("main", var("ps_main")) ) ) )
res = module_code(res, filename=__file__, name="datatypes.Main")
